name: chnroute

on: 
  release:
    types: [published]
#  push:
#    tags:
#    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: 0 17 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build ipset files
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        mkdir -p /opt/tmp/
        echo "create chnroute hash:net family inet" >chnroute.ipset
        wget -qO chnroute.txt https://raw.githubusercontent.com/pexcn/daily/gh-pages/chnroute/chnroute.txt
        sed 's/^/add chnroute /' chnroute.txt >> chnroute.ipset
        echo "create chnroute6 hash:net family inet6" >chnroute6.ipset
        wget -qO chnroute6.txt https://raw.githubusercontent.com/pexcn/daily/gh-pages/chnroute/chnroute-v6.txt
        sed 's/^/add chnroute6 /' chnroute6.txt >> chnroute6.ipset
        sudo cp chnroute.ipset /opt/tmp/
        sudo cp chnroute6.ipset /opt/tmp/
    - name: commit
      run: |
        git config --global user.email krisvictor3@gmail.com
        git config --global user.name kunwu3
        git add .
        git commit -m "update" -a	
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.R_TOKEN }}        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.R_TOKEN }}
        file: /opt/tmp/*
        tag: AutoBuild
        overwrite: true
        file_glob: true
